# Site settings
title: Foresight
description: "데이터 분석을 통해서 얻은 Foresight를 공유합니다."
url: "https://foresighters.github.io"
author:
  name: "Foresighters"
  email: "foresightersdev@gmail.com"
  url: "https://foresighters.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: "./posts"
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
